export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_VISIBILITY_FILTER = 'TOGGLE_VISIBILITY_FILTER';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const INCOMPLETE_TODO = 'INCOMPLETE_TODO';
export const INCOMPLETE_ALL = 'INCOMPLETE_ALL';
export const ADD_ABORTED = 'ADD_ABORTED';
